apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  namespace: yaobank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
